---
title: "index"
author: "Pablo Tiscornia"
date: "2022-11-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
```

```{r}
library(tidyverse)
library(googlesheets4)
library(reactable)
library(htmltools)
```


```{r base}
googlesheets4::gs4_deauth()
url <- "https://docs.google.com/spreadsheets/d/1xcYY1RkvOxnJlANMPtzhbdrpUgtSdF7IoEtNzE6zRKk/edit?usp=sharing"
b_paquetes <- read_sheet(url)
```

## Temáticas (en función del objetivo principal del paquete)

```{r}

banderas <- data.frame(
  pais = unique(b_paquetes$pais),
  bandera = paste0(":", "U+1F1E6", ":")
) |> 
  filter(!is.na(pais))

data <- b_paquetes |> 
  mutate(pais = paste0(pais, " ", "u+1f1e6")) |> 
  select(tematica, icono, paquete, pais, link)
  
data |> 
  reactable(filterable = TRUE, 
            searchable = TRUE,
            striped = TRUE,
            groupBy = "tematica",
            showPageSizeOptions = TRUE,
            showPagination = TRUE,
            minRows = 10,
            columns = list(
              tematica = colDef(name = "Temática"),
              paquete = colDef(
                name = "Paquete",
                html = TRUE, 
                cell = function(value, index) {
                  sprintf('<a href="%s" target="_blank">%s</a>', data$link[index], value)
                }),
              icono = colDef(cell = reactablefmtr::embed_img(height = 45, width = 45)),
              pais = colDef(name = "País"))
  )
  
```